### ISSUE TITLE
Exception after update to current version

### ISSUE THREAD

**Issue by oliver13** [escapestudios/EscapeWSSEAuthenticationBundle#58]
Hello !

EscapeWSSEAuthenticationBundle worked great for several months now, but after I updated to the latest version I get this error message if I try to clear the symfony cache:

[Symfony\Component\Debug\Exception\ContextErrorException]                                                                                                                                                 
Catchable Fatal Error: Argument 2 passed to MyAuthenticationProvider::__construct() must implement interface Symfony\Component\Security\Core\Encoder\PasswordEncoderInterface, string given, called in /cache-path/ap_DevDebugProjectContainer.php on line 1879 and defined 

Do you have an idea how to fix this ? 

Thanks in advance !

**Comment by oliver13** [comment]
OK, I had to insert the provider key in the constructor of my authentication provider. But now I have an other issue in the log file:

No Authentication Provider found for token of class "Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken

**Comment by djoos** [comment]
Hi @oliver13,

version 2.0.0 introduced some changes for people who are making use of custom authentication providers.

Could you double-check your auth provider's supports-method with [the one in the bundle](https://github.com/escapestudios/EscapeWSSEAuthenticationBundle/blob/master/Security/Core/Authentication/Provider/Provider.php)?

Alternatively, is there any way you could ping a gist with your auth provider - then I'll have a quick look...

Thanks in advance!

Kind regards,
David

**Comment by djoos** [comment]
* kick *

**Comment by oliver13** [comment]
Hello @djoos,

thank you for the fast answer and sorry for my late response. I have managed to get it to work again by checking the provider's methods in the bundle.

with kind regards

**Comment by djoos** [comment]
Perfect, thanks for your feedback @oliver13!

Kind regards,
David
