### ISSUE TITLE
Proper release tag?

### ISSUE THREAD

**Issue by bkosborne** [escapestudios/EscapeWSSEAuthenticationBundle#60]
I don't typically like to include @dev releases in a project, but it seems like there is no actual release for the 2.3 branch. Can you please release a version for this branch? Otherwise when running composer update I will bring in potentially unstable commits for this code. Thanks

**Comment by djoos** [comment]
Hi Brian,

thanks for getting in touch!

The bundle's semver releases don't go hand in hand with Symfony2's releases; 2.0.1 is the latest stable release and will run on 2.3 and upwards.

Hope this helps!

Kind regards,
David

**Comment by bkosborne** [comment]
Ah, that does help. Thanks!

**Comment by djoos** [comment]
You're welcome!
