### ISSUE TITLE
Deprecation warnings are failing unit tests

### ISSUE THREAD

**Issue by bkosborne** [escapestudios/EscapeWSSEAuthenticationBundle#66]
The [deprecation warning](https://github.com/symfony/Security/blob/2.7/Core/SecurityContextInterface.php) in the Symfony security component is causing unit tests to fail.

I don't know the proper way to handle this. You cannot "fix" the problem by not using the SecurityContextInterface, because you then break compatibility with older Symfony versions.

You also cannot tell phpunit to NOT convert these to errors. If you look [here](https://phpunit.de/manual/current/en/appendixes.configuration.html), you can see that we'd have to turn off `convertErrorsToExceptions` completely to fix this problem. You can't just have phpunit ignore deprecation errors w/o also ignoring all the other errors.

Do you have any idea on how best to resolve this?

**Comment by bkosborne** [comment]
Also interesting is that it was 2.6 that actually deprecated the SecurityContext service, but they didn't add the warning code until 2.7.

2.7 is not released yet, but since this projects composer.json has `"minimum-stability": "dev"` it will pick up on 2.7-dev.

**Comment by djoos** [comment]
Merged - thanks!
