### ISSUE TITLE
Co-maintain

### ISSUE THREAD

**Issue by bkosborne** [escapestudios/EscapeWSSEAuthenticationBundle#67]
Wondering if you'd consider adding me to help maintain this bundle. We're using it but there's a few improvement sand code style changes that can be made. If not I'll just work thru pull requests

**Comment by djoos** [comment]
Hi @bkosborne,

thanks for offering to help out with the bundle. For now we'd prefer the route of using PRs - we can then review/discuss adding you as a maintainer in the future... What do you think?

Thanks in advance for your feedback!

Kind regards,
David

**Comment by bkosborne** [comment]
Yea sure! Just wanted to see if you needed more immediate help.
