### ISSUE TITLE
nvalidArgumentException: This token has no "nonce" attribute. #57

### ISSUE THREAD

**Issue by vodoo22** [escapestudios/EscapeWSSEAuthenticationBundle#75]
I get this exception each request, i know this issue has been opened before, i added the below lines in config.yml as u said but still the same exception

escape_wsse_authentication:
    authentication_provider_class: Escape\WSSEAuthenticationBundle\Security\Core\Authentication\Provider\Provider
    authentication_listener_class: Escape\WSSEAuthenticationBundle\Security\Http\Firewall\Listener
    authentication_entry_point_class: Escape\WSSEAuthenticationBundle\Security\Http\EntryPoint\EntryPoint
    authentication_encoder_class: Symfony\Component\Security\Core\Encoder\MessageDigestPasswordEncoder

**Comment by djoos** [comment]
Hi @LazyDreamer22,

would you be able to give me some more information on your setup?
Which version of Symfony2 are you running? Any possibility you could share your firewall-config in security.yml with me?

Linking this to #69 for now.

Thanks in advance!

Kind regards,
David

**Comment by djoos** [comment]
Hi @LazyDreamer22,

 no need for the extra info - I think I got to the root of the issue: would you be able to give b38d8c1851bd6d6173a627d6f85ac756a8cc29be a go and let me know how that goes?

Thanks in advance for your feedback!

Kind regards,
David
