### ISSUE TITLE
Bundle ignores isEnabled() flag

### ISSUE THREAD

**Issue by felicitus** [escapestudios/EscapeWSSEAuthenticationBundle#76]
I configured `EscapeWSSEAuthenticationBundle` with `FOSUserBundle` as user provider. However, it seems that the enabled/disabled user flag is ignored.

I think that it should be checked if the user object returned by the user provider is an instance of `AdvancedUserInterface`, and if so, it should check for [isEnabled](http://api.symfony.com/2.4/Symfony/Component/Security/Core/User/AdvancedUserInterface.html#method_isEnabled) and proceed accordingly.

**Comment by djoos** [comment]
Hi @felicitus,

first of all sorry for the late reply. You're right here, handling an `AdvancedUserInterface` User is not part of the bundle as it stands.

Thanks for your initial work on this! I was wondering: should we try and delegate this to the [UserChecker.php](https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/Security/Core/User/UserChecker.php) instead?

Example providers: [UserAuthenticationProvider](https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/Security/Core/Authentication/Provider/UserAuthenticationProvider.php) and [DaoAuthenticationProvider](https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/Security/Core/Authentication/Provider/DaoAuthenticationProvider.php).

The big benefit of using the UserChecker is obviously that other than isEnabled(), isAccountNonLocked(), isAccountNonExpired() and isCredentialsNonExpired() are handled as well.

What do you think?

Thanks in advance for your feedback!
David

**Comment by djoos** [comment]
See PR #68, we'll try to get that PR merged in ASAP.

Kind regards,
David

**Comment by djoos** [comment]
Merged!
