### ISSUE TITLE
can't install bundle

### ISSUE THREAD

**Issue by lMoDy** [escapestudios/EscapeWSSEAuthenticationBundle#79]
symfony2 v.2.6

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package escapestudios/wsse-authentication-bundle could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by djoos** [comment]
Hi @lMoDy,

are you still experiencing this issue? If so, give me a shout and I'll reopen this thread!

Kind regards,
David
